---
title: "Chicago: Mapping Enterprise Zones and CTA L stops" 
author: "Emma Bonanno"
date: "9/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Packages

```{r load packages, message=FALSE}
library(sf)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(dplyr)
library(ggplot2)
```

## Downloading and Naming Data
```{r downloading data}
Ezones <- st_read("https://data.cityofchicago.org/api/geospatial/64xf-pyvh?method=export&format=KML") 

Lstops <- st_read("https://data.cityofchicago.org/download/4qtv-9w43/application%2Fxml")
```

## Practicing with Plots

```{r}
Lstops_plot <- ggplot(Lstops) +
  geom_sf() 
Lstops_plot
```
```{r changing color and shape}
ggplot(Lstops) +
  geom_sf(shape = 17, color = "blue") 
```
```{r changing point size}
ggplot(Lstops) +
  geom_sf(shape = 18, color = "red", size = 0.5) 
```
```{r changing transparency}
ggplot(Lstops) +
  geom_sf(shape = 18, color = "red", alpha = 0.1) 
```
```{r}
ggplot(Lstops) +
  geom_sf() +
  geom_sf(data = Ezones) 
```
```{r changing the layering order}
ggplot() +
  geom_sf(data = Ezones) +
  geom_sf(data = Lstops, color = "red") 
```
```{r}
ggplot() +
  geom_sf(data = Ezones, color = "red",
                        fill = "red",
                        alpha = 0.5) +
  geom_sf(data = Lstops, color = "blue", size = 0.5)
```
```{r creating a legend}
ggplot() +
  geom_sf(data = Ezones, color = NA,alpha = 0.5,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops, color = "blue") +
  scale_fill_manual(values = "red", name = "")
```
```{r making two legends}
ggplot() +
  geom_sf(data = Ezones, color = NA,alpha = 0.5,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops,
          size = 0.5,
          aes(color = "CTA - L stops")) +
  scale_fill_manual(values = "red", name = "") +
  scale_color_manual(values = "blue", name = "")
```
```{r changing background color}
ggplot() +
  geom_sf(data = Ezones, color = NA,alpha = 0.5,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops,
          size = 0.5,
          aes(color = "CTA - L stops")) +
  scale_fill_manual(values = "red", name = "") +
  scale_color_manual(values = "blue", name = "") +
  theme(panel.background = element_rect(fill = "white"),
        legend.key = element_rect(fill = "white"))
```
```{r same thing but easier}
ggplot() +
  geom_sf(data = Ezones, color = NA,alpha = 0.5,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops,
          size = 0.5,
          aes(color = "CTA - L stops")) +
  scale_fill_manual(values = "red", name = "") +
  scale_color_manual(values = "blue", name = "") +
  theme_void()
```
```{r}
ggplot() +
  geom_sf(data = Ezones, color = NA,alpha = 0.5,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops,
          size = 0.5,
          aes(color = "CTA - L stops")) +
  scale_fill_manual(values = "red", name = "") +
  scale_color_manual(values = "blue", name = "") +
  theme_map()
```
```{r}
ggplot(Lstops) + 
  annotation_map_tile(zoomin = 0, progress = "none") +
  geom_sf()+
  labs(caption = "Map tiles and data by OpenStreetMap")
```
```{r}
ggplot(Lstops) + 
  geom_sf() +
  geom_sf(data = Ezones) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw") +
  geom_sf()+
  labs(caption = "Map tiles and data by OpenStreetMap")
```
```{r plotting data on top of a basemap}
ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight")  +
  geom_sf() +
  labs(caption = "Map tiles and data by OpenStreetMap")+
  geom_sf(data = Ezones, color = "red",
                        fill = "red",
                        alpha = 0.5) +
  geom_sf(data = Lstops, color = "blue", size = 0.5) 
  
```
```{r plotting on top of a basemap with a legend}
ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight")  +
  geom_sf() +
  labs(caption = "Map tiles and data by OpenStreetMap")+
  geom_sf(data = Ezones, color = NA,alpha = 0.5,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops,
          size = 0.5,
          aes(color = "CTA - L stops")) +
  scale_fill_manual(values = "red", name = "") +
  scale_color_manual(values = "blue", name = "") +
  theme_void()
```
```{r}
ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight")  +
  geom_sf() +
  labs(caption = "Map tiles and data by OpenStreetMap")+
  geom_sf(data = Ezones, color = "red",alpha = 0.2,
                        aes(fill = "Enterprise Zones")) +
  geom_sf(data = Lstops,
          size = 0.5,
          aes(color = "CTA - L stops")) +
  scale_fill_manual(values = "red", name = "") +
  scale_color_manual(values = "blue", name = "") +
  theme_void()
```
